# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6275df80d7d37ba64e7cf59bd2bb2943878837d0650c2fe57aea92d8e344d10e6ff4d8898d35617fd0020240a1423e5b9ada96670508b9ddeea7e7140c26615b

test:
  secret_key_base: 7a567b088f7e8b2a9a5033289c70963043557d5e40049cdf9eb55b65dacefda0182a530db977e1b0078f7c51e8a4077b71a5817e23588b1f0c322788cef3eeee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
